create table user (
    id int generated by default as identity,
    user_id varchar(45) not null,
    password text  not null,
    email varchar(45) not null,
    invite_url text not null,
    activate tinyint(1) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table tag (
    id int generated by default as identity,
    user_id int not null,
    tag_name varchar(45) not null,
    disclosure tinyint(1) not null,
    activate tinyint(1) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table notification (
    id int generated by default as identity,
    user_id int not null,
    target_user_id int not null,
    shared_schedule_id int,
    notification_type varchar(10) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table shared_schedule(
    id int generated by default as identity,
    user_id int not null,
    connectee_id int not null,
    content text not null,
    date timestamp null,
    activate tinyint(1) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table schedule (
    id int generated by default as identity,
    user_id int not null,
    tag_id int not null,
    content text not null,
    date timestamp not null,
    active tinyint(1) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table connector (
    id int generated by default as identity,
    connector_id int not null,
    connectee_id int not null,
    last_visited_at timestamp not null,
    activate tinyint(1) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

alter table tag add foreign key (user_id) references user(id);
alter table notification add foreign key (user_id) references user(id);
alter table notification add foreign key (target_user_id) references user(id);
alter table notification add foreign key (shared_schedule_id) references shared_schedule(id);
alter table shared_schedule add foreign key (user_id) references user(id);
alter table shared_schedule add foreign key (connectee_id) references user(id);
alter table schedule add foreign key (user_id) references user(id);
alter table schedule add foreign key (tag_id) references tag(id);
alter table connector add foreign key (connector_id) references user(id);
alter table connector add foreign key (connectee_id) references user(id);