create table USER
(
    id              int generated by default as identity,
    user_id         varchar(45) not null,
    password        varchar(60) not null,
    email           varchar(45) not null,
    invite_url_code text        not null,
    activate        tinyint     not null,
    try_count       int         not null,
    created_at      timestamp   not null default current_timestamp,
    updated_at      timestamp   not null default current_timestamp on update current_timestamp,
    password_date   timestamp   not null default current_timestamp,
    primary key (id)
);

create table NOTIFICATION
(
    id                 int generated by default as identity,
    user_id            int         not null,
    target_user_id     int         not null,
    shared_schedule_id int,
    notification_type  varchar(10) not null,
    created_at         timestamp   not null default current_timestamp,
    updated_at         timestamp   not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table SHARED_SCHEDULE
(
    id           int generated by default as identity,
    user_id      int       not null,
    connectee_id int       not null,
    content      text      not null,
    date         timestamp null,
    activate     tinyint   not null,
    created_at   timestamp not null default current_timestamp,
    updated_at   timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table CONNECTOR
(
    id              int generated by default as identity,
    connector_id    int       not null,
    connectee_id    int       not null,
    last_visited_at timestamp not null,
    activate        tinyint   not null,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id)
);

alter table NOTIFICATION
    add foreign key (user_id) references USER (id);
alter table NOTIFICATION
    add foreign key (target_user_id) references USER (id);
alter table NOTIFICATION
    add foreign key (shared_schedule_id) references SHARED_SCHEDULE (id);
alter table SHARED_SCHEDULE
    add foreign key (user_id) references USER (id);
alter table SHARED_SCHEDULE
    add foreign key (connectee_id) references USER (id);
alter table CONNECTOR
    add foreign key (connector_id) references USER (id);
alter table CONNECTOR
    add foreign key (connectee_id) references USER (id);


INSERT INTO USER(user_id,
                 password,
                 email,
                 invite_url_code,
                 activate,
                 try_count,
                 password_date,
                 created_at,
                 updated_at)
VALUES ('dbsdk7865',
        '$2a$10$jzHMQj...0ESbVwyEWmBZO3JrnZnry0EUlXmUtqi47ew5bDSMwiUi',
        'dbsdk7865@naver.com',
        'QWERASDFZXCV',
        true,
        0,
        NOW(),
        NOW(),
        NOW());

INSERT INTO USER(user_id,
                 password,
                 email,
                 invite_url_code,
                 activate,
                 try_count,
                 password_date,
                 created_at,
                 updated_at)
VALUES ('dbsdk7864',
        '$2a$10$jzHMQj...0ESbVwyEWmBZO3JrnZnry0EUlXmUtqi47ew5bDSMwiUi',
        'dbsdk7865@naver.com',
        'QWERASDFZXC1',
        true,
        0,
        NOW(),
        NOW(),
        NOW());


INSERT INTO USER(user_id,
                 password,
                 email,
                 invite_url_code,
                 activate,
                 try_count,
                 password_date,
                 created_at,
                 updated_at)
VALUES ('dbsdk7863',
        '$2a$10$jzHMQj...0ESbVwyEWmBZO3JrnZnry0EUlXmUtqi47ew5bDSMwiUi',
        'dbsdk7865@naver.com',
        'QWERASDFZXC2',
        true,
        0,
        NOW(),
        NOW(),
        NOW());


INSERT INTO USER(user_id,
                 password,
                 email,
                 invite_url_code,
                 activate,
                 try_count,
                 password_date,
                 created_at,
                 updated_at)
VALUES ('dbsdk7862',
        '$2a$10$jzHMQj...0ESbVwyEWmBZO3JrnZnry0EUlXmUtqi47ew5bDSMwiUi',
        'dbsdk7865@naver.com',
        'QWERASDFZXC3',
        true,
        0,
        NOW(),
        NOW(),
        NOW());

INSERT INTO CONNECTOR(connector_id, connectee_id, last_visited_at, activate, created_at, updated_at)
VALUES (1, 2, NOW(), 1, NOW(), NOW());

INSERT INTO CONNECTOR(connector_id, connectee_id, last_visited_at, activate, created_at, updated_at)
VALUES (3, 1, NOW(), 1, NOW(), NOW());

INSERT INTO CONNECTOR(connector_id, connectee_id, last_visited_at, activate, created_at, updated_at)
VALUES (1, 4, NOW(), 0, NOW(), NOW());

INSERT INTO CONNECTOR(connector_id, connectee_id, last_visited_at, activate, created_at, updated_at)
VALUES (2, 3, NOW(), 1, NOW(), NOW());

INSERT INTO CONNECTOR(connector_id, connectee_id, last_visited_at, activate, created_at, updated_at)
VALUES (3, 4, NOW(), 1, NOW(), NOW());

INSERT INTO CONNECTOR(connector_id, connectee_id, last_visited_at, activate, created_at, updated_at)
VALUES (2, 4, NOW(), 1, NOW(), NOW());
