create table USER
(
    id            int generated by default as identity,
    user_id       varchar(45) not null,
    password      text        not null,
    email         varchar(45) not null,
    invite_url    text        not null,
    activate      tinyint     not null,
    try_count     int         not null,
    created_at    timestamp   not null default current_timestamp,
    updated_at    timestamp   not null default current_timestamp on update current_timestamp,
    password_date timestamp   not null default current_timestamp,
    primary key (id)
);

create table NOTIFICATION
(
    id                 int generated by default as identity,
    user_id            int         not null,
    target_user_id     int         not null,
    shared_schedule_id int,
    notification_type  varchar(10) not null,
    created_at         timestamp   not null default current_timestamp,
    updated_at         timestamp   not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table SHARED_SCHEDULE
(
    id           int generated by default as identity,
    user_id      int       not null,
    connectee_id int       not null,
    content      text      not null,
    date         timestamp null,
    like_count   int       not null default 0,
    activate     tinyint   not null,
    created_at   timestamp not null default current_timestamp,
    updated_at   timestamp not null default current_timestamp on update current_timestamp,
    primary key (id)
);

create table CONNECTOR
(
    id              int generated by default as identity,
    connector_id    int       not null,
    connectee_id    int       not null,
    last_visited_at timestamp not null,
    activate        tinyint   not null,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id)
);

create table HEART
(
    id          int generated by default as identity,
    user_id     int        not null,
    shared_schedule_id int        not null,
    is_like     tinyint(1) not null,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id)
);

alter table NOTIFICATION
    add foreign key (user_id) references USER (id);
alter table NOTIFICATION
    add foreign key (target_user_id) references USER (id);
alter table NOTIFICATION
    add foreign key (shared_schedule_id) references SHARED_SCHEDULE (id);
alter table SHARED_SCHEDULE
    add foreign key (user_id) references USER (id);
alter table SHARED_SCHEDULE
    add foreign key (connectee_id) references USER (id);
alter table CONNECTOR
    add foreign key (connector_id) references USER (id);
alter table CONNECTOR
    add foreign key (connectee_id) references USER (id);
alter table HEART
    add foreign key (user_id) references USER (id);
alter table HEART
    add foreign key (shared_schedule_id) references SHARED_SCHEDULE (id);
